name: Build and push container image

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  container:
    if: github.repository_owner == 'Lightprotocol'
    name: container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/Lightprotocol/light-anchor

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Copy amd64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker create \
            --name temp_container \
            --platform linux/amd64 \
            ${{ env.REGISTRY }}/Lightprotocol/light-anchor:${{ steps.meta.outputs.tags[0] }}
          docker cp temp_container:/usr/local/bin/light-anchor ./light-anchor-amd64
          docker rm -f temp_container

      - name: Copy arm64 binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker create \
            --name temp_container \
            --platform linux/arm64 \
            ${{ env.REGISTRY }}/Lightprotocol/light-anchor:${{ steps.meta.outputs.tags[0] }}
          docker cp temp_container:/usr/local/bin/light-anchor ./light-anchor-arm64
          docker rm -f temp_container

      - name: Create GitHub release and upload binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
          gh release create ${{ github.ref }} \
            ./light-anchor-amd64 \
            ./light-anchor-arm64 \
            --title "Release ${{ github.ref }}"

      - name: Setup Rust
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Instal cargo-workspaces
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces

      - name: Publish to crates.io
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cargo workspaces publish \
            --all --exact --no-git-tag --no-git-commit \
            --token ${{ secrets.CRATES_IO_TOKEN }}
